name: holodoodler-dev37
channels:
  - conda-forge
  - defaults
dependencies:
 - python=3.7
 - tifffile
 - CairoSVG
 - matplotlib
 - scipy
 - numpy
 - scikit-image
 - Pillow
 - scikit-learn
 - cairo
 - tqdm
 - psutil
 - jupyterlab
 - holoviews
 - panel
 - flake8
 - pytest
 - pytest-cov
 - plotly
 - pydensecrf
 - gdal
 - pip
 - pip:
   - doodler-engine
